# Generated by Django 5.0.6 on 2024-06-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_productimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="created_at",
            new_name="create_at",
        ),
    ]
