# Generated by Django 5.0.6 on 2024-06-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_rename_created_at_productimage_create_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                default="products/default.png", upload_to="products/"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                default="product_images/default.png", upload_to="product_images/"
            ),
        ),
    ]
