# Generated by Django 5.0.6 on 2024-06-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="crated_by",
            new_name="created_by",
        ),
    ]
